version: '2'
services:
  backend:
    container_name: palindrome
    build:
      context: ./
      dockerfile: ./Dockerfile/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - mysql
      - react
      - redis
      - swagger-ui
#      - native
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
  mysql:
    image: mysql
    container_name: mysql
    build:
      context: ./
      dockerfile: ./Dockerfile/MysqlDockerfile
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - app-network
  react:
    container_name: react
    build:
      context: .
      dockerfile: ./Dockerfile/ReactDockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/v1.yaml
#  native:
#    container_name: native
#    build:
#      context: ./
#      dockerfile: ./Dockerfile/ReactNativeDockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
networks:
  app-network:
    driver: "bridge"
